#!/bin/bash
yum update -y
yum install git -y
yum install -y docker
amazon-linux-extras install java-openjdk11 -y
wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
amazon-linux-extras install epel -y
yum install jenkins -y
systemctl start jenkins
systemctl enable jenkins
usermod -aG docker jenkins
systemctl start docker
systemctl restart jenkins